machine already startedTEMP DIR: /tmp/tmp.dm02q8dBC4Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 433B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.7s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/6] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/6] WORKDIR /app
#5 CACHED

#6 [3/6] RUN git clone https://github.com/psf/black.git
#6 0.278 Cloning into 'black'...
#6 DONE 6.6s

#7 [4/6] WORKDIR /app/black
#7 DONE 0.1s

#8 [5/6] RUN pip install -r test_requirements.txt
#8 2.173 Collecting coverage>=5.3
#8 3.395   Downloading coverage-7.5.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (232 kB)
#8 3.534      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.9/232.9 kB 1.8 MB/s eta 0:00:00
#8 3.632 Collecting pre-commit
#8 3.643   Downloading pre_commit-3.5.0-py2.py3-none-any.whl (203 kB)
#8 3.769      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.7/203.7 kB 1.8 MB/s eta 0:00:00
#8 3.879 Collecting pytest>=6.1.1
#8 3.891   Downloading pytest-8.2.1-py3-none-any.whl (339 kB)
#8 4.039      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 339.6/339.6 kB 2.3 MB/s eta 0:00:00
#8 4.093 Collecting pytest-xdist>=3.0.2
#8 4.103   Downloading pytest_xdist-3.6.1-py3-none-any.whl (46 kB)
#8 4.135      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.1/46.1 kB 1.5 MB/s eta 0:00:00
#8 4.202 Collecting pytest-cov>=4.1.0
#8 4.221   Downloading pytest_cov-5.0.0-py3-none-any.whl (21 kB)
#8 4.377 Collecting tox
#8 4.387   Downloading tox-4.15.0-py3-none-any.whl (155 kB)
#8 4.470      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.7/155.7 kB 1.9 MB/s eta 0:00:00
#8 4.516 Collecting cfgv>=2.0.0
#8 4.527   Downloading cfgv-3.4.0-py2.py3-none-any.whl (7.2 kB)
#8 4.579 Collecting nodeenv>=0.11.1
#8 4.588   Downloading nodeenv-1.8.0-py2.py3-none-any.whl (22 kB)
#8 4.734 Collecting virtualenv>=20.10.0
#8 4.745   Downloading virtualenv-20.26.2-py3-none-any.whl (3.9 MB)
#8 6.487      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 2.3 MB/s eta 0:00:00
#8 6.594 Collecting pyyaml>=5.1
#8 6.609   Downloading PyYAML-6.0.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (736 kB)
#8 6.890      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 736.6/736.6 kB 2.6 MB/s eta 0:00:00
#8 7.011 Collecting identify>=1.0.0
#8 7.023   Downloading identify-2.5.36-py2.py3-none-any.whl (98 kB)
#8 7.053      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.0/99.0 kB 3.3 MB/s eta 0:00:00
#8 7.100 Collecting pluggy<2.0,>=1.5
#8 7.111   Downloading pluggy-1.5.0-py3-none-any.whl (20 kB)
#8 7.152 Collecting exceptiongroup>=1.0.0rc8
#8 7.274   Downloading exceptiongroup-1.2.1-py3-none-any.whl (16 kB)
#8 7.370 Collecting tomli>=1
#8 7.379   Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
#8 7.416 Collecting iniconfig
#8 7.432   Downloading iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
#8 7.480 Collecting packaging
#8 7.489   Downloading packaging-24.0-py3-none-any.whl (53 kB)
#8 7.515      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.5/53.5 kB 1.9 MB/s eta 0:00:00
#8 7.563 Collecting execnet>=2.1
#8 7.573   Downloading execnet-2.1.1-py3-none-any.whl (40 kB)
#8 7.591      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.6/40.6 kB 2.7 MB/s eta 0:00:00
#8 7.708 Collecting filelock>=3.13.1
#8 7.736   Downloading filelock-3.14.0-py3-none-any.whl (12 kB)
#8 7.786 Collecting cachetools>=5.3.2
#8 7.807   Downloading cachetools-5.3.3-py3-none-any.whl (9.3 kB)
#8 7.848 Collecting chardet>=5.2
#8 7.861   Downloading chardet-5.2.0-py3-none-any.whl (199 kB)
#8 7.962      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.4/199.4 kB 2.3 MB/s eta 0:00:00
#8 8.019 Collecting colorama>=0.4.6
#8 8.030   Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
#8 8.123 Collecting platformdirs>=4.1
#8 8.142   Downloading platformdirs-4.2.2-py3-none-any.whl (18 kB)
#8 8.197 Collecting pyproject-api>=1.6.1
#8 8.205   Downloading pyproject_api-1.6.1-py3-none-any.whl (12 kB)
#8 8.262 Requirement already satisfied: setuptools in /usr/local/lib/python3.8/site-packages (from nodeenv>=0.11.1->pre-commit->-r test_requirements.txt (line 2)) (57.5.0)
#8 8.355 Collecting distlib<1,>=0.3.7
#8 8.363   Downloading distlib-0.3.8-py2.py3-none-any.whl (468 kB)
#8 8.544      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.9/468.9 kB 2.6 MB/s eta 0:00:00
#8 8.683 Installing collected packages: distlib, tomli, pyyaml, pluggy, platformdirs, packaging, nodeenv, iniconfig, identify, filelock, execnet, exceptiongroup, coverage, colorama, chardet, cfgv, cachetools, virtualenv, pytest, pyproject-api, tox, pytest-xdist, pytest-cov, pre-commit
#8 9.856 Successfully installed cachetools-5.3.3 cfgv-3.4.0 chardet-5.2.0 colorama-0.4.6 coverage-7.5.1 distlib-0.3.8 exceptiongroup-1.2.1 execnet-2.1.1 filelock-3.14.0 identify-2.5.36 iniconfig-2.0.0 nodeenv-1.8.0 packaging-24.0 platformdirs-4.2.2 pluggy-1.5.0 pre-commit-3.5.0 pyproject-api-1.6.1 pytest-8.2.1 pytest-cov-5.0.0 pytest-xdist-3.6.1 pyyaml-6.0.1 tomli-2.0.1 tox-4.15.0 virtualenv-20.26.2
#8 9.857 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#8 9.993 
#8 9.993 [notice] A new release of pip is available: 23.0.1 -> 24.0
#8 9.993 [notice] To update, run: pip install --upgrade pip
#8 DONE 10.2s

#9 [6/6] RUN pytest
#9 0.926 ============================= test session starts ==============================
#9 0.926 platform linux -- Python 3.8.19, pytest-8.2.1, pluggy-1.5.0
#9 0.926 rootdir: /app/black
#9 0.926 configfile: pyproject.toml
#9 0.926 plugins: xdist-3.6.1, cov-5.0.0
#9 0.926 collected 1 item / 8 errors
#9 0.926 
#9 0.926 ==================================== ERRORS ====================================
#9 0.926 _____________________ ERROR collecting tests/test_black.py _____________________
#9 0.926 ImportError while importing test module '/app/black/tests/test_black.py'.
#9 0.926 Hint: make sure your test modules/packages have valid Python names.
#9 0.926 Traceback:
#9 0.926 /usr/local/lib/python3.8/importlib/__init__.py:127: in import_module
#9 0.926     return _bootstrap._gcd_import(name[level:], package, level)
#9 0.926 tests/test_black.py:35: in <module>
#9 0.926     import click
#9 0.926 E   ModuleNotFoundError: No module named 'click'
#9 0.926 ____________________ ERROR collecting tests/test_blackd.py _____________________
#9 0.926 ImportError while importing test module '/app/black/tests/test_blackd.py'.
#9 0.926 Hint: make sure your test modules/packages have valid Python names.
#9 0.926 Traceback:
#9 0.926 /usr/local/lib/python3.8/importlib/__init__.py:127: in import_module
#9 0.926     return _bootstrap._gcd_import(name[level:], package, level)
#9 0.926 tests/test_blackd.py:6: in <module>
#9 0.926     from click.testing import CliRunner
#9 0.926 E   ModuleNotFoundError: No module named 'click'
#9 0.926 _____________________ ERROR collecting tests/test_docs.py ______________________
#9 0.926 ImportError while importing test module '/app/black/tests/test_docs.py'.
#9 0.926 Hint: make sure your test modules/packages have valid Python names.
#9 0.926 Traceback:
#9 0.926 /usr/local/lib/python3.8/importlib/__init__.py:127: in import_module
#9 0.926     return _bootstrap._gcd_import(name[level:], package, level)
#9 0.926 tests/test_docs.py:14: in <module>
#9 0.926     from black.mode import UNSTABLE_FEATURES, Preview
#9 0.926 E   ModuleNotFoundError: No module named 'black'
#9 0.926 ____________________ ERROR collecting tests/test_format.py _____________________
#9 0.926 ImportError while importing test module '/app/black/tests/test_format.py'.
#9 0.926 Hint: make sure your test modules/packages have valid Python names.
#9 0.926 Traceback:
#9 0.926 /usr/local/lib/python3.8/importlib/__init__.py:127: in import_module
#9 0.926     return _bootstrap._gcd_import(name[level:], package, level)
#9 0.926 tests/test_format.py:7: in <module>
#9 0.926     import black
#9 0.926 E   ModuleNotFoundError: No module named 'black'
#9 0.926 _____________________ ERROR collecting tests/test_ipynb.py _____________________
#9 0.926 ImportError while importing test module '/app/black/tests/test_ipynb.py'.
#9 0.926 Hint: make sure your test modules/packages have valid Python names.
#9 0.926 Traceback:
#9 0.926 /usr/local/lib/python3.8/importlib/__init__.py:127: in import_module
#9 0.926     return _bootstrap._gcd_import(name[level:], package, level)
#9 0.926 tests/test_ipynb.py:10: in <module>
#9 0.926     from click.testing import CliRunner
#9 0.926 E   ModuleNotFoundError: No module named 'click'
#9 0.926 ___________________ ERROR collecting tests/test_no_ipynb.py ____________________
#9 0.926 ImportError while importing test module '/app/black/tests/test_no_ipynb.py'.
#9 0.926 Hint: make sure your test modules/packages have valid Python names.
#9 0.926 Traceback:
#9 0.926 /usr/local/lib/python3.8/importlib/__init__.py:127: in import_module
#9 0.926     return _bootstrap._gcd_import(name[level:], package, level)
#9 0.926 tests/test_no_ipynb.py:4: in <module>
#9 0.926     from click.testing import CliRunner
#9 0.926 E   ModuleNotFoundError: No module named 'click'
#9 0.926 ____________________ ERROR collecting tests/test_ranges.py _____________________
#9 0.926 ImportError while importing test module '/app/black/tests/test_ranges.py'.
#9 0.926 Hint: make sure your test modules/packages have valid Python names.
#9 0.926 Traceback:
#9 0.926 /usr/local/lib/python3.8/importlib/__init__.py:127: in import_module
#9 0.926     return _bootstrap._gcd_import(name[level:], package, level)
#9 0.926 tests/test_ranges.py:7: in <module>
#9 0.926     from black.ranges import adjusted_lines, sanitized_lines
#9 0.926 E   ModuleNotFoundError: No module named 'black'
#9 0.926 _____________________ ERROR collecting tests/test_trans.py _____________________
#9 0.926 ImportError while importing test module '/app/black/tests/test_trans.py'.
#9 0.926 Hint: make sure your test modules/packages have valid Python names.
#9 0.926 Traceback:
#9 0.926 /usr/local/lib/python3.8/importlib/__init__.py:127: in import_module
#9 0.926     return _bootstrap._gcd_import(name[level:], package, level)
#9 0.926 tests/test_trans.py:3: in <module>
#9 0.926     from black.trans import iter_fexpr_spans
#9 0.926 E   ModuleNotFoundError: No module named 'black'
#9 0.926 =========================== short test summary info ============================
#9 0.926 ERROR tests/test_black.py
#9 0.926 ERROR tests/test_blackd.py
#9 0.926 ERROR tests/test_docs.py
#9 0.926 ERROR tests/test_format.py
#9 0.926 ERROR tests/test_ipynb.py
#9 0.926 ERROR tests/test_no_ipynb.py
#9 0.926 ERROR tests/test_ranges.py
#9 0.926 ERROR tests/test_trans.py
#9 0.926 !!!!!!!!!!!!!!!!!!! Interrupted: 8 errors during collection !!!!!!!!!!!!!!!!!!!!
#9 0.926 ============================== 8 errors in 0.33s ===============================
#9 ERROR: process "/bin/sh -c pytest" did not complete successfully: exit code: 2
------
 > [6/6] RUN pytest:
0.926 ERROR tests/test_black.py
0.926 ERROR tests/test_blackd.py
0.926 ERROR tests/test_docs.py
0.926 ERROR tests/test_format.py
0.926 ERROR tests/test_ipynb.py
0.926 ERROR tests/test_no_ipynb.py
0.926 ERROR tests/test_ranges.py
0.926 ERROR tests/test_trans.py
0.926 !!!!!!!!!!!!!!!!!!! Interrupted: 8 errors during collection !!!!!!!!!!!!!!!!!!!!
0.926 ============================== 8 errors in 0.33s ===============================
------
Dockerfile:17
--------------------
  15 |     
  16 |     # Run tests to verify the installation
  17 | >>> RUN pytest
--------------------
ERROR: failed to solve: process "/bin/sh -c pytest" did not complete successfully: exit code: 2
removing docker image...clearing temp directory